### ISSUE TITLE
Random initial guess

### ISSUE THREAD

**Issue by loforteg** [pvalenzuelac/econ622#3]
Hi Pablo!
In Problem Set 3, Exercise 4 Intro to Types, I would check that you can find a root for any random starting point.
For example: 

``` julia
# Random initial guess
x0 = rand(-100:100)
q = Polynomial([-56, -1, 1])
@show length(q)
v_old, normdiff, iter = newtonsmethod(q, x0) 
```

What do you think?

**Comment by pvalenzuelac** [comment]
That's a good point @loforteg ! Ty
